apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rest-image-db-pvc
spec:
  # storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rest-image-db-pv
  labels:
    type: local
spec:
  # storageClassName: generic
  claimRef:
    namespace: default
    name: rest-image-db-pvc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo"
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  labels:          
    app: rest-image-db
  name: rest-image-db 
spec:         
  replicas: 1    
  selector: 
    matchLabels:
      app: rest-image-db
  template:
    metadata:
      labels:
        app: rest-image-db
    spec:
      containers:
      - name: mongodb
        volumeMounts:
          - mountPath: /var/lib/mongo
            name: mongo-rest-image-db
        image: mongo:4.2
        ports:
        - containerPort: 27017
      volumes:
      - name: mongo-rest-image-db
        persistentVolumeClaim:
          claimName: rest-image-db-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-image-db
  name: rest-image-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: rest-image-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-image
  name: rest-image
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rest-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-image
    version: v1
  name: rest-image
  namespace: default
spec:
  selector:
    matchLabels:
      app: rest-image
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-image
        version: v1
    spec:
      serviceAccountName: rest-image
      containers:
        - image: docker.io/cmwylie19/rest-image:latest
          name: rest-image
          env:
            - name: SECRET
              value: SECRET
            - name: MONGO_URL
              value: mongodb://rest-image-db:27017
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rest-image